# Generated by Django 4.2 on 2026-05-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'Custom User', 'verbose_name_plural': 'Custom Users'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='organization_role',
            field=models.CharField(choices=[('User', 'Regular User'), ('OSAS', 'OSAS Administrator'), ('Property', 'Property Manager')], db_index=True, default='User', max_length=20),
        ),
    ]
