services:
  - type: web
    name: pelec-api
    runtime: python
    rootDir: backend

    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn backend.wsgi:application"

    envVars:
      - key: PYTHON_VERSION
        value: "3.11"

      # Set in Render dashboard (recommended)
      - key: SECRET_KEY
        value: ""
      - key: DEBUG
        value: "False"

      - key: DATABASE_URL
        fromDatabase:
          name: event-management-db
          property: postgresql://event_management_db_y0qd_user:73cEOp2hfX6uQ6BQvHjmdG7u0TppshQ8@dpg-d80t8g7avr4c73arnl40-a/event_management_db_y0qd

      - key: ALLOWED_HOSTS
        value: "yourdomain.onrender.com,www.yourdomain.onrender.com"
      - key: FRONTEND_URLS
        value: "https://event-management-indol-phi.vercel.app/"

databases:
  - name: event-management-db
    plan: standard
    region: singapore
