# Generated by Django 4.2 on 2026-05-05 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_eventapplication_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='eventapplication',
            table='event_applications',
        ),
    ]
