# Generated by Django 4.2 on 2026-05-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_eventapplication_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Event Application', 'verbose_name_plural': 'Event Applications'},
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='equipment',
            field=models.TextField(blank=True, default='[]', help_text='Store as JSON string'),
        ),
    ]
