# Generated by Django 4.2 on 2026-05-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_eventapplication_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventapplication',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventapplication',
            name='start_date',
            field=models.DateField(blank=True, help_text='Alias for event_date', null=True),
        ),
    ]
