# Generated by Django 5.2.7 on 2026-05-09 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_eventapplication_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('equipment_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('borrowed', 'Borrowed'), ('maintenance', 'Maintenance'), ('damaged', 'Damaged')], db_index=True, default='available', max_length=20)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='excellent', max_length=20)),
                ('quantity_available', models.IntegerField(default=1)),
                ('quantity_total', models.IntegerField(default=1)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'db_table': 'equipment',
                'ordering': ['equipment_id'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentBorrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_borrowed', models.IntegerField(default=1)),
                ('borrow_date', models.DateTimeField(auto_now_add=True)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active (Currently Borrowed)'), ('returned', 'Returned'), ('damaged_return', 'Returned - Damaged')], db_index=True, default='active', max_length=20)),
                ('condition_on_return', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('damage_notes', models.TextField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to='dashboard.equipment')),
                ('event_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_records', to='dashboard.eventapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_borrows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipment Borrow Record',
                'verbose_name_plural': 'Equipment Borrow Records',
                'db_table': 'equipment_borrow_records',
                'ordering': ['-borrow_date'],
            },
        ),
    ]
